version: '3'
services:
  ktor:
    container_name: stasbar-ktor
    build: backend
    env_file: .env
    restart: unless-stopped
    environment:
      PORT: "8080"
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@stasbar-db:5432/${DATABASE_USER}"
    ports:
      - 8000:8080
    depends_on:
      - db

  db:
    container_name: stasbar-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
