package com.stasbar.app.gplayapi

// Generated with https://www.json2kotlin.com/
data class AppDetails(
  val title: String,
  val description: String,
  val descriptionHTML: String,
  val summary: String,
  val installs: String,
  val minInstalls: Int,
  val score: Double,
  val scoreText: Double,
  val ratings: Int,
  val reviews: String,
  val histogram: Map<String, Int>,
  val price: Double,
  val free: Boolean,
  val currency: String,
  val priceText: String,
  val offersIAP: Boolean,
  val size: String,
  val androidVersion: Double,
  val androidVersionText: String,
  val developer: Developer,
  val developerId: String,
  val developerEmail: String,
  val developerWebsite: String,
  val developerAddress: String,
  val privacyPolicy: String,
  val developerInternalID: String,
  val genre: String,
  val genreId: String,
  val icon: String,
  val headerImage: String,
  val screenshots: List<String>,
  val contentRating: String,
  val adSupported: Boolean,
  val released: String,
  val updated: String,
  val version: String,
  val recentChanges: String,
  val comments: List<String>,
  val appId: String,
  val url: String,
  val playstoreUrl: String,
  val permissions: String,
  val similar: String
)
